---
- name: Ubuntu provisioning
  hosts: local
  tasks:
    - name: Install Desktop
      apt:
        name: 
          - xfce4
          - xfce4-goodies  
          - slim
        install_recommends: no    
        state: present

    - name: Set default target to X
      command: 'systemctl set-default graphical'  
