---
- name: Ubuntu provisioning
  hosts: local
  tasks:
    - name: Install Tasksel
      apt:
        name: tasksel
        install_recommends: yes    
        state: present

    - name: Install desktop
      command: 'tasksel install mate-desktop'        

    - name: Set default target to X
      command: 'systemctl set-default graphical'  
