---
- name: Ubuntu provisioning
  hosts: localhost
  become: yes
  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jdk
        - docker
        - docker-compose
        - maven

    - name: Install snap packages
      snap:
        name: "{{ item }}"
        classic: yes
      loop:
        - intellij-idea-community
        - code
        - netbeans  
        - postman

    - name: Check if Pulse VPN is installed
      shell: 'dpkg-query -W pulse | cut -c -5'
      register: pulse_installed 
      changed_when: pulse_installed.stdout != 'pulse'

    - include_tasks: pulse.yml
      when: pulse_installed.stdout != 'pulse'  
      
    - name: Install tasksel
      apt:
        name: tasksel
        install_recommends: yes    
        state: present

    - name: Check if xubuntu-desktop is installed
      shell: 'dpkg-query -W xubuntu-desktop | cut -c -15'
      register: xubuntu_installed
      changed_when: xubuntu_installed.stdout != "xubuntu-desktop"

    - name: Install desktop
      command: 'tasksel install xubuntu-desktop'
      when: xubuntu_installed.stdout != "xubuntu-desktop"
      ignore_errors: yes
      


