---
- name: Ubuntu provisioning
  hosts: local
  become: yes
  tasks:
    - name: Install Tasksel
      apt:
        name: tasksel
        install_recommends: yes    
        state: present

    - name: Install desktop
      command: 'tasksel install xubuntu-desktop'

   
