---
- name: Ubuntu provisioning
  hosts: localhost
  become: yes
  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - openjdk-8-jdk
        - docker
        - docker-compose
        - maven

    - name: Install snap packages
      snap:
        name: "{{ item }}"
        classic: yes
      loop:
        - intellij-idea-community
        - code
        - netbeans  
        - postman

    - name: Check if Pulse VPN is installed
      shell: 'dpkg-query -W pulse | cut -c -5'
      register: pulse_installed 
      changed_when: pulse_installed.stdout != 'pulse'

    - name: Install tasksel
      apt:
        name: tasksel
        install_recommends: yes    
        state: present

    - name: Check if xubuntu-desktop is installed
      shell: 'dpkg-query -W xubuntu-desktop | cut -c -15'
      register: xubuntu_installed
      changed_when: xubuntu_installed.stdout != "xubuntu-desktop"
      
    - include_tasks: pulse.yml
      when: 
        - pulse_installed.stdout != 'pulse'
        - xubuntu_installed.stdout == "xubuntu-desktop"      

    - name: Check if Soap script exist
      stat: 
        path: /home/vagrant/.soap
      register: soap_exist
      changed_when: soap_exist.stat.exists == false
        
    - name: Create directory
      file:
        path: /home/vagrant/Desktop
        state: directory
        owner: vagrant
        group: vagrant
        
    - name: Download SoapUI
      get_url:
        url: "https://s3.amazonaws.com/downloads.eviware/soapuios/5.6.0/SoapUI-x64-5.6.0.sh"
        dest: "/home/vagrant/Desktop/SoapUI-x64-5.6.0.sh"
        owner: vagrant
        group: vagrant
        mode: '0755'
      when: 
        - xubuntu_installed.stdout == "xubuntu-desktop"
        - soap_exist.stat.exists == false
        
    - name: Create soap file that prevents multiple downloads
      file:
        path: /home/vagrant/.soap
        state: touch
        owner: vagrant
        group: vagrant
      when: 
        - soap_exist.stat.exists == false
        - xubuntu_installed.stdout == "xubuntu-desktop"
        
    - name: Disable ubuntu user
      user:
        name: ubuntu
        state: absent

    - name: Install desktop
      command: 'tasksel install xubuntu-desktop'
      when: xubuntu_installed.stdout != "xubuntu-desktop"
      ignore_errors: yes
                     
 
      


